import type { CopyMap } from '../types'

export const defaultCopy = {
  appName: '墨迹面板',
  brandSubtitle: '任务有序，人情不忘',
  syncCloud: '云同步',
  syncLocal: '本地预览',
  navOverview: '总览',
  navTodos: '待办',
  navBirthdays: '生日',
  navMentors: '大佬',
  customize: '定制',
  doneCustomizing: '完成定制',
  resetDefault: '恢复默认',
  save: '保存',
  cancel: '取消',
  close: '关闭',
  edit: '编辑',
  delete: '删除',
  signOut: '退出登录',
  birthdayReminderEyebrow: '北京时间 20:00 生日提醒',
  heroTitle: '把眼前事与重要的人，都稳稳放在手边',
  localPreviewNotice: '当前为本地预览模式。填入 Supabase 环境变量后，Android 和 Windows 会自动使用云同步。',
  loadingBoot: '正在开卷',
  loadingData: '正在取数',
  overviewEyebrow: '今日总览',
  overviewTitle: '案头清爽，心里就有余地',
  statActiveTodos: '未完成',
  statDoneTodos: '已完成',
  statBirthdayAlerts: '三日生日',
  statMentors: '维护对象',
  upcomingTodos: '近期待办',
  newTodo: '新待办',
  birthdayOrder: '生日顺序',
  addBirthday: '记生日',
  mentorCare: '大佬维护',
  addMentor: '加记录',
  emptyUpcomingTodos: '暂无临近截止的待办',
  emptyBirthdays: '暂无生日记录',
  emptyMentors: '暂无维护记录',
  listEyebrow: '清单',
  todosTitle: '待办任务',
  birthdaysTitle: '生日清单',
  mentorsTitle: '大佬维护清单',
  emptyTodos: '还没有待办',
  newTodoTitle: '新建待办',
  editTodoTitle: '编辑待办',
  todoTitleLabel: '标题',
  todoTitlePlaceholder: '这件事叫什么',
  todoDetailsLabel: '具体要求',
  todoDetailsPlaceholder: '验收标准、背景、注意事项',
  statusLabel: '状态',
  priorityLabel: '优先级',
  dueDateLabel: '截止时间',
  statusTodo: '待启',
  statusDoing: '进行',
  statusDone: '已成',
  priorityLow: '从容',
  priorityMedium: '适中',
  priorityHigh: '要紧',
  overdue: '逾期',
  today: '今日',
  daysLater: '天后',
  editBirthdayTitle: '编辑生日',
  newBirthdayTitle: '记录生日',
  nameLabel: '姓名',
  birthdayNamePlaceholder: '要记住谁',
  monthLabel: '月份',
  dayLabel: '日期',
  birthYearLabel: '出生年份',
  optionalPlaceholder: '可不填',
  relationshipLabel: '关系',
  relationshipPlaceholder: '朋友、家人、同学',
  notesLabel: '备注',
  birthdayNotesPlaceholder: '礼物、祝福、忌口',
  editMentorTitle: '编辑维护',
  newMentorTitle: '记录大佬',
  mentorNamePlaceholder: '对方怎么称呼',
  helpedWithLabel: '帮助过我的事',
  helpedWithPlaceholder: '对方给过什么建议、资源或关键帮助',
  reportCycleLabel: '汇报周期',
  daysPlaceholder: '天数',
  lastReportedLabel: '上次汇报',
  mentorNotesPlaceholder: '下次汇报重点、对方偏好',
  reportSuggestionTitle: '下次汇报建议',
  reportDraftButton: '生成汇报草稿',
  reportTimelineTitle: '汇报时间线',
  newReportTitle: '新增汇报',
  editReportTitle: '编辑汇报',
  reportDateLabel: '汇报日期',
  reportContentLabel: '汇报内容',
  reportContentPlaceholder: '这次汇报了什么进展',
  reportFeedbackLabel: '反馈/结果',
  reportFeedbackPlaceholder: '对方反馈、资源或结论',
  nextStepsLabel: '下一步计划',
  nextStepsPlaceholder: '下次要交付或推进什么',
  addReport: '保存汇报',
  updateReport: '更新汇报',
  noReports: '还没有汇报记录',
  noReportCycle: '未设周期',
  reportOverduePrefix: '已过 ',
  reportOverdueSuffix: ' 天',
  reportToday: '今日可汇报',
  reportEverySuffix: '天一汇报',
  reportCountSuffix: '条汇报',
  authCloudEnabled: '云端同步已开启',
  authEyebrow: '个人面板',
  authTitle: '先落座，再开卷',
  emailLabel: '邮箱',
  passwordLabel: '密码',
  login: '登录',
  createAccount: '创建账号',
  firstUseCreate: '第一次使用，创建账号',
  backToLogin: '已有账号，返回登录',
  copyEditorTitle: '编辑文案',
  copyEditorHint: '这会改变界面上的静态文字，不会改你的任务、生日或汇报数据。',
  copyValueLabel: '文案内容',
  copyValuePlaceholder: '写下你喜欢的表达',
} as const satisfies CopyMap

export type CopyKey = keyof typeof defaultCopy

export function mergeCopy(copy?: CopyMap | null): CopyMap {
  return {
    ...defaultCopy,
    ...(copy ?? {}),
  }
}
